### ISSUE TITLE
无法复现模型效果

### ISSUE THREAD

**Issue by ApolloRay** [IDEA-CCNL/Fooocus-Taiyi-XL#1]
`pipeline_text2image = StableDiffusionXLPipeline.from_single_file(
        "/taiyi_diffusion_xl.safetensors", torch_dtype=torch.float16, variant="fp16", use_safetensors=True
    ).to("cuda")
    prompt = "一个宇航员骑着白马"
    neg_prompt = ""
    generator = torch.Generator(torch.device("cuda")).manual_seed(1234)
    num_inference_steps = 50
    guidance_scale = 7
    image = pipeline_text2image(
            prompt=prompt,
            negative_prompt=neg_prompt,
            height=1024,
            width=1024,
            generator=generator, 
            num_inference_steps=num_inference_steps,
            guidance_scale=guidance_scale).images[0]
`
无法获得一个宇航员骑着白马应用的展示效果。请问是否可以提供一个diffusers的推理结果呢？

**Comment by wxj630** [comment]
我们主要测试的是Fooocus推理，因为可以提供很多预设好的质量词、风格词、负向提示词，还没有在diffusers严格测试过，我们推荐可以到我们搭建的在线demo体验：https://huggingface.co/spaces/IDEA-CCNL/Taiyi-Stable-Diffusion-XL-3.5B

We mainly test Fooocus inference, because it can provide many preset quality words and style words and negative prompt. We didn't strictly test our model on diffusers. We recommend you to experience the online demo we built: https://huggingface.co/spaces /IDEA-CCNL/Taiyi-Stable-Diffusion-XL-3.5B
